[server]
address = "127.0.0.1:1883"

[client]
id = "pepper_gw"

[topic]
sub_topic = "ctrl/#"
pub_topic = "v1/gateway/telemetry"

[msg]
example = "{\"label\": \"SN-001\"}"
template = "{<{label}>: 1}"

[database]
path = "./"
name = "test.db"
