[log]
file_path = "log/gw.log"
file_path_pattern = "log/gw{}.log.gz"
# error, warn, info, debug, trace
level = "info"
# The size limit in bytes.
size = 1048576  #1*1024*1024
# The maximum number of archived logs to maintain
count = 5

[server]
address = "127.0.0.1:1883"

[client]
id = "pepper_gw"
keep_alive = 60
username = "pepper_gw"

[topic]
sub_topic = "ctrl/#"
pub_topic = "v1/gateway/telemetry"
qos = 0

[msg]
example = "{\"id\":1,\"name\":\"SN-001\",\"temperature\": 27.45,\"humidity\": 25.36,\"voltage\": 3.88,\"status\": 0}"
template = "{<{name}>: [{\"ts\": <#TS#>,\"values\": {\"temperature\": <{temperature}>, \"humidity\": <{humidity}>,\"voltage\": <{voltage}>,\"status\": <{status}>}}]}"

[database]
path = "./"
name = "iot.db"

[data_if]
#if_name = "/dev/ttyS14"
#if_type = "serial_port"
if_name = "./data_if.txt"
if_type = "text_file"
