[package]
name = "data_management"
version = "0.1.0"
authors = ["Dell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.23.1"
